### ISSUE TITLE
Execution failed for task ':compileBuildConfig'. java.lang.reflect.UndeclaredThrowableException

### ISSUE THREAD

**Issue by GO3LIN** [sourcerer-io/sourcerer-app#280]
Hello, I tried building the app but got this error:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileBuildConfig'.
> > java.lang.reflect.UndeclaredThrowableException

Here's my java -version output: 

```
λ java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```
And finally, the stack trace:

```
 * Exception is:
 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileBuildConfig'.
         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
         at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
         at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
         at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
         at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
         at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
         at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
         at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
         at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
         at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
         at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
         at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
         at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
         at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
         at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
         at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)
         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
 Caused by: java.lang.RuntimeException: java.lang.reflect.UndeclaredThrowableException
         at com.sun.tools.javac.api.JavacTool.getTask(jdk.compiler@9-internal/JavacTool.java:180)
         at com.sun.tools.javac.api.JavacTool.getTask(jdk.compiler@9-internal/JavacTool.java:109)
         at com.sun.tools.javac.api.JavacTool.getTask(jdk.compiler@9-internal/JavacTool.java:65)
         at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.createCompileTask(JdkJavaCompiler.java:67)
         at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:49)
         at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
         at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:98)
         at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:51)
         at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
         at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
         at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
         at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:156)
         at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:141)
         at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:114)
         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
         at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
         at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
         at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
         at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
         ... 29 more
 Caused by: java.lang.reflect.UndeclaredThrowableException
         at com.sun.proxy.$Proxy76.handleOption(Unknown Source)
         at com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.handleOption(jdk.compiler@9-internal/ClientCodeWrapper.java:265)
         at com.sun.tools.javac.main.Arguments.doProcessArgs(jdk.compiler@9-internal/Arguments.java:375)
         at com.sun.tools.javac.main.Arguments.processArgs(jdk.compiler@9-internal/Arguments.java:294)
         at com.sun.tools.javac.main.Arguments.init(jdk.compiler@9-internal/Arguments.java:250)
         at com.sun.tools.javac.api.JavacTool.getTask(jdk.compiler@9-internal/JavacTool.java:175)
         ... 54 more
 Caused by: java.lang.IllegalAccessException: class org.gradle.api.internal.tasks.compile.reflect.SourcepathIgnoringInvocationHandler cannot access class com.sun.tools.javac.file.BaseFileManager (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.file to unnamed module @26a3a42d
         at org.gradle.api.internal.tasks.compile.reflect.SourcepathIgnoringInvocationHandler.invoke(SourcepathIgnoringInvocationHandler.java:65)
         ... 60 more
```

**Comment by anatolykislov** [comment]
Hi @GO3LIN 

Try to update your gradle to latest version.

**Comment by GO3LIN** [comment]
Hello, I am already on the latest version 4.7, I tried downgrading to 4.6 but in vain.

**Comment by GO3LIN** [comment]
```
λ sdk install gradle 4.8
 
Stop! gradle 4.8 is not available. Possible causes:
 * 4.8 is an invalid version
 * gradle binaries are incompatible with Linux64
```
hmm.. Don't you have a docker image ?

**Comment by GO3LIN** [comment]
Well, I was able to add a repository but this one doesn't appear on my profile page.
I was firstly asked to enter a new email address because the one that I have used is not present in any commit, so I added the one I was using. I think that this is why the stats doesn't appear on my profile, because in my sourcerer account, I only see 1 email address. Isn't it ?

**Comment by GO3LIN** [comment]
That was my bad, I was building the default branch (develop) after cloning the repository. 
Going to close this. Thanks @anatolykislov

**Comment by lecchereng** [comment]
I had the same issue because I had jre instead of jdk installed.
TO SOLVE install jdk 8.
